language:
  - cpp

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      env: BUILD_TYPE=Debug   STD=c++0x
    - os: linux
      env: BUILD_TYPE=Debug   STD=c++11
    - os: linux
      env: BUILD_TYPE=Release STD=c++0x
    - os: linux
      env: BUILD_TYPE=Release STD=c++11

env: STD=c++11

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - mkdir build && cd build

script:
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS="-std=${STD}"
  - make

branches:
  only:
    - master
    - develop
