language:
  - cpp

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      env: BUILD_TYPE=Debug   STD=c++0x
    - os: linux
      env: BUILD_TYPE=Debug   STD=c++11
    - os: linux
      env: BUILD_TYPE=Release STD=c++0x
    - os: linux
      env: BUILD_TYPE=Release STD=c++11

env: STD=c++11

before_script:
    - mkdir build && cd build

script:
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS="-std=${STD}"
    - make

branches:
  only:
    - master
    - develop
